_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "checkpoints/coco/faster_rcnn_R_50_FPN_cls_ag_b/model_reset_remove.pth"
  WEIGHTS: 'checkpoints/coco/faster_rcnn_R_50_FPN_fc_fsdet_base/model_reset_remove.pth'
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
    FREEZE_BOX_HEAD: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: False
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: False
    FREEZE_WITHOUT_PREDICTOR: True
  BACKBONE:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_novel_5shot_seed9',)
  TEST: ('coco_test_novel',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (20000,)
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 1500
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_50_FPN_ft_fsdet_novel_5shot"