_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/nfsmirror/faster_rcnn/seed0/mask_rcnn_R_50_FPN_fullclsag_metric_finetunedw_cos_bh_all_10shot/model_final.pth"
  BACKBONE:
    FREEZE: true
  MASK_ON: true
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: TRUE
  ROI_HEADS:
    FREEZE_BOX_HEAD: true
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: true
    FREEZE: true
DATASETS:
  TRAIN: ('coco_trainval_novel_10shot_seed9',)
  TEST: ('coco_test_all',)
SOLVER:
  #Initial FsDet settings
#  IMS_PER_BATCH: 16
#  BASE_LR: 0.001
#  STEPS: (14400,)
#  MAX_ITER: 16000
#  CHECKPOINT_PERIOD: 1000
#  WARMUP_ITERS: 10
  #End Initial FsDet Settings
  #Our settings - We do same epchs as novel finetuning + 10 more
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  STEPS: (15000,)
  MAX_ITER: 16000 
  CHECKPOINT_PERIOD: 160000 
  WARMUP_ITERS: 0 
#  WARMUP_ITERS: 0
# End our settings
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/mask_rcnn_R_50_FPN_ft_fullclsag_cos_bh_all_10shot/"
TEST:
  EVAL_PERIOD: 1000 
