_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "checkpoints/coco/faster_rcnn_R_50_FPN_fc_fullclsag_base_split1/model_reset.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 60
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_BOX_HEAD: False
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: True
    FREEZE: True
  BACKBONE:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_base_split1',)
  TEST: ('coco_test_base_split1',)
SOLVER:
# Berkeley 30 shot LR + steps for base. (Probably can do with less)
  BASE_LR: 0.0007
  IMS_PER_BATCH: 8
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  WARMUP_ITERS: 20 # Taken from 30-shot settings
# Original values:
# --------------------
# IMS_PER_BATCH: 16
# BASE_LR: 0.02
# STEPS: (60000, 80000)
# MAX_ITER: 90000

# Berkeley 30-shot settings
#IMS_PER_BATCH: 16
#BASE_LR: 0.001
#STEPS: (216000,)
#MAX_ITER: 240000
#CHECKPOINT_PERIOD: 12000
#WARMUP_ITERS: 10
# End Berkeley 30-shot settings
OUTPUT_DIR: "checkpoints/nfsmirror/faster_rcnn_R_50_ft_fullclsag_cos_bh_split1_base"
# OUTPUT_DIR: "checkpoints/coco/faster_rcnn_R_50_ft_fullclsag_cos_bh_split1_base"
