_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn_R_50_ft_fullclsag_cos_bh_base/model_reset_remove.pth"
  BACKBONE:
    FREEZE: true
  MASK_ON: true
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: TRUE
  ROI_HEADS:
    FREEZE_BOX_HEAD: true
    NUM_CLASSES: 20
    OUTPUT_LAYER: "CosineSimOutputLayers"
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: true
#    FREEZE: true
    FREEZE_WITHOUT_PREDICTOR: True
DATASETS:
  TRAIN: ('coco_trainval_novel_1shot_seed9',)
  TEST: ('coco_test_novel',)
SOLVER:
# Two GPU 5-shot settings.
#    BASE_LR: 0.005
#  CHECKPOINT_PERIOD: 300
#    IMS_PER_BATCH: 8
#    MAX_ITER: 3000
#    STEPS: !!python/tuple
#      - 20000
#    WARMUP_ITERS: 0
# End two-GPU 5-shot settings
# Our settings:
    IMS_PER_BATCH: 8
    BASE_LR: 0.005
    STEPS: (20000,)
    MAX_ITER: 1000
    CHECKPOINT_PERIOD: 5000
    WARMUP_ITERS: 0
# End our settings

OUTPUT_DIR: 'checkpoints/coco/mask_rcnn_R_50_FPN_ft_fullclsag_cos_bh_nofreezemaskpred_novel_1shot'
#OUTPUT_DIR: "checkpoints/coco/faster_rcnn/mask_rcnn_R_50_FPN_ft_fullclsag_cos_bh_novel_5shot"