_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:

#  WEIGHTS: "checkpoints/coco/faster_rcnn_R_50_FPN_cls_ag_b/model_reset_remove.pth"
  WEIGHTS: "checkpoints/nfsmirror/faster_rcnn_R_50_FPN_ft_cos_bh_base/model_0089999.pth"
  BACKBONE:
    FREEZE: true
  MASK_ON: true
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: false
  ROI_HEADS:
    FREEZE_BOX_HEAD: true
    NUM_CLASSES: 20 # Number of classes in the TEST file
    OUTPUT_LAYER: "CosineSimOutputLayers"
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: true
    FREEZE: true
DATASETS:
  TRAIN: ('coco_trainval_novel_5shot_seed9',)
  TEST: ('coco_test_novel',)
SOLVER:
# Two GPU 5-shot settings.
#    BASE_LR: 0.005
#  CHECKPOINT_PERIOD: 300
#    IMS_PER_BATCH: 8
#    MAX_ITER: 3000
#    STEPS: !!python/tuple
#      - 20000
#    WARMUP_ITERS: 0
# End two-GPU 5-shot settings
# Our settings:
    BASE_LR: 0.0025
    CHECKPOINT_PERIOD: 600
    IMS_PER_BATCH: 4
    MAX_ITER: 6000
    STEPS: !!python/tuple
      - 40000
    WARMUP_ITERS: 0
# End our settings
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_50_metric_avg_novel_cos_bh_5shot_test"