_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/mask_rcnn_R_50_FPN_fsdet_combined_weights_all_5shot/model_final.pth"
  MASK_ON: true
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 80
    FREEZE_BOX_HEAD: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: False
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: False
    FREEZE_WITHOUT_PREDICTOR: True
  BACKBONE:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_5shot_seed8',)
  TEST: ('coco_test_all',)
SOLVER:
  #Initial FsDet settings
#  IMS_PER_BATCH: 16
#  BASE_LR: 0.001
#  STEPS: (14400,)
#  MAX_ITER: 16000
#  CHECKPOINT_PERIOD: 1000
#  WARMUP_ITERS: 10
  #End Initial FsDet Settings
  #Our settings - We do same epchs as novel finetuning + 10 more
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  STEPS: (72000, )
  MAX_ITER: 80000 
  # CHECKPOINT_PERIOD: 1000 
  WARMUP_ITERS: 0 
#  WARMUP_ITERS: 0
# End our settings
# OUTPUT_DIR: "checkpoints/coco/faster_rcnn/mask_rcnn_R_50_FPN_ft_fullclsag_cos_bh_all_5shot_manyiters/"
# OUTPUT_DIR: "checkpoints/nfsmirror/faster_rcnn/mask_rcnn_R_50_FPN_ft_fullclsag_cos_bh_all_5shot_manyiters_V2/"
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/mask_rcnn_R_50_FPN_ft_fsdet_all_5shot_manyiters/"
TEST:
  EVAL_PERIOD: 1000
