DATASETS:
  TEST: !!python/tuple
  - coco_test_novel
  TRAIN: !!python/tuple
  - coco_trainval_novel_5shot_seed7
MODEL:
  BACKBONE:
    FREEZE: true
  MASK_ON: true
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: false
  ROI_HEADS:
    FREEZE_BOX_HEAD: true
    NUM_CLASSES: 20
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: true
    FREEZE: true
  WEIGHTS: checkpoints/coco/faster_rcnn_R_50_FPN_cls_ag_b/model_reset_remove.pth
OUTPUT_DIR: ./checkpoints/nfsmirror/faster_rcnn/seed7/mask_rcnn_R_50_FPN_ft_novel_5shot
SOLVER:
  BASE_LR: 0.005
  CHECKPOINT_PERIOD: 300
  IMS_PER_BATCH: 8
  MAX_ITER: 3000
  STEPS: !!python/tuple
  - 20000
  WARMUP_ITERS: 0
_BASE_: ../../Base-RCNN-FPN.yaml
